create table if not exists T_CONFIG
(
    CODE VARCHAR2(32),
    V VARCHAR2(256)
);

CREATE TABLE IF NOT EXISTS T_PAGE
(
    ID VARCHAR2(32),
    TITLE VARCHAR2(256),
    CONTENT TEXT,
    CREATE_AT DATETIME,
    UPDATE_AT DATETIME,
    STATUS TINYINT(4) default 1,
    DESC VARCHAR2(256),
    BG_URL VARCHAR2(256)
);


CREATE TABLE IF NOT EXISTS T_REPLY
(
    ID VARCHAR2(32),
    PAGE_ID VARCHAR2(32),
    IP VARCHAR2(256),
    CONTENT TEXT,
    CREATE_AT DATETIME,
    STATUS TINYINT(4) default 0
);

CREATE TABLE IF NOT EXISTS T_TAG
(
    ID VARCHAR2(32),
    TAG VARCHAR2(64),
);

CREATE TABLE IF NOT EXISTS T_PAGE_TAG
(
    PAGE_ID VARCHAR2(32),
    TAG_ID VARCHAR2(32)
);