CREATE TABLE IF NOT EXISTS T_EXTRACT
(
    ID VARCHAR(32),
    TYPE TINYINT comment '类别1图片2文章3文本段落',
    TITLE VARCHAR(256),
    CONTENT TEXT comment '',
    SOURCE_URL VARCHAR(512),
    STATUS TINYINT DEFAULT 1,
    MEMO VARCHAR(512),
    CREATE_AT TIMESTAMP,
    UPDATE_AT TIMESTAMP
);